stages:
- name: Build
  steps:
  - runScriptConfig:
      image: amazoncorretto:11
      shellScript: |-
        mkdir -p /tomcat/src/github.com/rancher
        ln -s `pwd` /tomcat/src/github.com/rancher/pipeline-example-go
        cd /tomcat/src/github.com/rancher/pipeline-example-go
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-helloserver:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
notification:
  recipients:
  - recipient: apps-notifications
    notifier: c-6t7tf:n-2tfj9
  condition:
  - Success
  - Changed
  - Failed
